# Generated by Django 5.1.3 on 2024-11-12 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_day_timeslot'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTulink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_major', models.CharField(max_length=100)),
                ('tutoring_major', models.CharField(max_length=100)),
                ('tutoring_sub_major', models.CharField(blank=True, max_length=100, null=True)),
                ('available_days', models.TextField()),
                ('available_times', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Day',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='tutor',
        ),
        migrations.DeleteModel(
            name='TimeSlot',
        ),
        migrations.RemoveField(
            model_name='tutor',
            name='user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='major',
        ),
        migrations.RemoveField(
            model_name='user',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='usertulink',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='webapp.user'),
        ),
        migrations.DeleteModel(
            name='Schedule',
        ),
        migrations.DeleteModel(
            name='Tutor',
        ),
    ]
