# Generated by Django 5.1.3 on 2024-11-12 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_user_id_alter_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertulink',
            name='user',
        ),
    ]
