# Generated by Django 5.1.3 on 2024-11-12 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_remove_user_role_user_my_available_days_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertulink',
            name='current_major',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='usertulink',
            name='tutoring_major',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='usertulink',
            name='tutoring_sub_major',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
