# Generated by Django 5.1.3 on 2024-11-12 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_alter_usertulink_current_major_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertulink',
            name='current_major',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='usertulink',
            name='tutoring_major',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='usertulink',
            name='tutoring_sub_major',
            field=models.TextField(blank=True, null=True),
        ),
    ]
