# Generated by Django 5.1.3 on 2024-11-13 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_alter_usertulink_current_major_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertulink',
            name='college',
            field=models.TextField(blank=True, null=True),
        ),
    ]
