# Generated by Django 5.1.3 on 2024-11-13 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0009_usertulink_college'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoTulink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college', models.TextField(blank=True, null=True)),
                ('major', models.TextField(blank=True, null=True)),
                ('sub_major', models.TextField(blank=True, null=True)),
                ('available_times', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.user')),
            ],
        ),
    ]
